from .catalog import DiagnosticCatalog
from .model import DiagnosticDefinition


def default_catalog():
    catalog = DiagnosticCatalog()
    definitions = [
        DiagnosticDefinition(
            "UNSUPPORTED_SYNTAX",
            "critical",
            "Unsupported manufacturing syntax",
            "Input contains constructs not interpreted by the parser.",
            "Add parser support or review with a trusted CAM tool.",
        ),
        DiagnosticDefinition(
            "CONNECTIVITY_CONFLICT",
            "error",
            "Connectivity conflict",
            "Independent evidence sources disagree about electrical connectivity.",
            "Inspect geometry, via span, and source net evidence.",
        ),
        DiagnosticDefinition(
            "UNRESOLVED_COMPONENT",
            "warning",
            "Unresolved component",
            "A component candidate cannot be classified with sufficient evidence.",
            "Review footprint geometry, silkscreen, and BOM evidence.",
        ),
        DiagnosticDefinition(
            "LOW_CONFIDENCE",
            "warning",
            "Low-confidence inference",
            "Inference confidence is below the review threshold.",
            "Add independent evidence or keep the result unresolved.",
        ),
        DiagnosticDefinition(
            "PROVENANCE_MISSING",
            "error",
            "Missing provenance",
            "A derived object lacks traceable source evidence.",
            "Repair evidence/provenance links before release.",
        ),
        DiagnosticDefinition(
            "GERBER_ARC_INVALID",
            "warning",
            "Invalid Gerber arc",
            "Gerber arc geometry is inconsistent.",
            "Inspect the arc endpoints, center offsets, quadrant mode, and source units.",
        ),
        DiagnosticDefinition(
            "GERBER_REGION_OPEN",
            "warning",
            "Open Gerber region",
            "Gerber region was not closed.",
            "Review the G36/G37 contour and close the source region before reconstruction.",
        ),
        DiagnosticDefinition(
            "GERBER_REGION_CUTIN_INVALID",
            "warning",
            "Invalid Gerber region cut-in",
            "Gerber cut-in geometry violates the supported fully-coincident axis-aligned bridge rules.",
            "Review the region contour or process it with a CAM tool that supports the source construct.",
        ),
        DiagnosticDefinition(
            "GERBER_REGION_CUTIN_DIRECTION_MISMATCH",
            "warning",
            "Gerber cut-in direction mismatch",
            "All cut-ins in one contour must share one horizontal or vertical direction.",
            "Review the source contour and split or correct incompatible cut-ins.",
        ),
        DiagnosticDefinition(
            "GERBER_REGION_CUTIN_WINDING_INVALID",
            "warning",
            "Gerber cut-in winding mismatch",
            "Cut-in hole winding must oppose the enclosing shell.",
            "Correct the contour winding in the source data or review with a trusted CAM tool.",
        ),
        DiagnosticDefinition(
            "GERBER_REGION_CUTIN_TOUCH_INVALID",
            "warning",
            "Gerber cut-in boundary contact",
            "Cut-in bridges may contact contour boundaries only at their endpoints.",
            "Review the source region for self-touching or ambiguous cut-in geometry.",
        ),
        DiagnosticDefinition(
            "GERBER_REGION_CUTIN_DISJOINT_UNSUPPORTED",
            "warning",
            "Disjoint Gerber cut-in result",
            "A fully-coincident cut-in resolves to disjoint filled areas that are not modeled yet.",
            "Review the source region in a CAM tool or add explicit support before reconstruction.",
        ),
        DiagnosticDefinition(
            "APERTURE_MACRO_UNSUPPORTED",
            "warning",
            "Unsupported aperture macro",
            "Aperture macro contains unsupported semantics.",
            "Simplify the macro to the supported subset or review it with a trusted CAM tool.",
        ),
        DiagnosticDefinition(
            "KICAD_PARSE_ERROR",
            "error",
            "KiCad parse error",
            "KiCad S-expression input could not be parsed.",
            "Validate the KiCad source file and inspect the reported syntax location.",
        ),
        DiagnosticDefinition(
            "MULTILAYER_SPAN_UNKNOWN",
            "warning",
            "Unknown multilayer span",
            "Layer span is not established by evidence.",
            "Add drill, stackup, or padstack evidence before asserting multilayer connectivity.",
        ),
        DiagnosticDefinition(
            "UNKNOWN_LAYER",
            "warning",
            "Unknown manufacturing layer",
            "Gerber syntax was detected, but the PCB layer could not be inferred from X2 attributes or the filename.",
            "Provide X2 FileFunction metadata or a filename that identifies the intended PCB layer.",
        ),
        DiagnosticDefinition(
            "PARSER_FAILURE",
            "error",
            "Parser failure",
            "A manufacturing file could not be scanned successfully.",
            "Inspect the parser error and source file before reconstruction.",
        ),
        DiagnosticDefinition(
            "GERBER_ZERO_SIZE_OBJECT_NO_IMAGE",
            "info",
            "Zero-size Gerber object",
            "A legal zero-diameter circular aperture object has no image effect.",
            "No action is required unless the zero-size object was unexpected.",
        ),
        DiagnosticDefinition(
            "GERBER_UNITS_UNDECLARED",
            "warning",
            "Gerber units not declared",
            "Gerber dimensional data appeared before an explicit unit declaration.",
            "Add a valid MO, G70, or G71 unit declaration before dimensional data.",
        ),
        DiagnosticDefinition(
            "CONFLICTING_GERBER_UNITS",
            "warning",
            "Conflicting Gerber units",
            "Gerber unit mode changed after units were already declared.",
            "Use one consistent unit system for the file.",
        ),
        DiagnosticDefinition(
            "INVALID_GERBER_FILE_POLARITY",
            "warning",
            "Invalid Gerber file polarity",
            "The X2 .FilePolarity attribute is malformed.",
            "Correct the X2 FilePolarity attribute to Positive or Negative.",
        ),
        DiagnosticDefinition(
            "CONFLICTING_GERBER_FILE_POLARITY",
            "warning",
            "Conflicting Gerber file polarity",
            "The file contains conflicting X2 .FilePolarity values.",
            "Use one consistent FilePolarity value and regenerate the manufacturing output.",
        ),
        DiagnosticDefinition(
            "UNSUPPORTED_GERBER_NEGATIVE_FILE_POLARITY",
            "warning",
            "Unsupported negative Gerber file polarity",
            "Negative Gerber file polarity requires whole-image inversion, which is not modeled safely.",
            "Regenerate as positive polarity or review the file with a trusted CAM tool.",
        ),
        DiagnosticDefinition(
            "GERBER_FILE_POLARITY_POSITIVE",
            "info",
            "Positive Gerber file polarity",
            "Positive X2 .FilePolarity uses presence-of-material image semantics.",
            "No action is required.",
        ),
        DiagnosticDefinition(
            "INVALID_GERBER_LAYER_POLARITY",
            "warning",
            "Invalid Gerber layer polarity",
            "The Gerber LP layer-polarity command is malformed.",
            "Correct the LP command before reconstruction.",
        ),
        DiagnosticDefinition(
            "GERBER_CLEAR_POLARITY_REGION_COMPOSITION",
            "info",
            "Gerber clear-polarity composition",
            "Clear-polarity material is composed by ordered subtraction from prior dark material.",
            "Review the resulting geometry when source data uses complex clear operations.",
        ),
        DiagnosticDefinition(
            "NON_CIRCULAR_DRAW",
            "warning",
            "Unsupported non-circular arc draw",
            "The requested arc interpolation cannot be represented safely with the active aperture semantics.",
            "Review the aperture and interpolation mode or regenerate the Gerber using supported geometry.",
        ),
        DiagnosticDefinition(
            "GERBER_STEP_REPEAT_LIMIT",
            "warning",
            "Gerber step-repeat limit exceeded",
            "Gerber step-and-repeat expansion exceeds the configured safety bound.",
            "Reduce the repeat count or split the source artwork into smaller inputs.",
        ),
        DiagnosticDefinition(
            "MALFORMED_EXCELLON_ROUTE",
            "warning",
            "Malformed Excellon route",
            "An Excellon linear routing command is malformed.",
            "Correct the route command syntax and rerun reconstruction.",
        ),
        DiagnosticDefinition(
            "EXCELLON_ROUTE_STATE",
            "warning",
            "Invalid Excellon route state",
            "An Excellon routing command violates the supported tool-down/tool-up state machine.",
            "Review the G00/M15/G01-or-arc/M16 sequence and tool selection.",
        ),
        DiagnosticDefinition(
            "EXCELLON_ROUTE_EMPTY",
            "warning",
            "Empty Excellon route",
            "An Excellon routed path ended without a segment.",
            "Add a routed segment before raising the tool or remove the empty route.",
        ),
        DiagnosticDefinition(
            "EXCELLON_ROUTE_UNTERMINATED",
            "warning",
            "Unterminated Excellon route",
            "End of file was reached while the route tool was still down.",
            "Terminate the route with M16 or M17 before the file ends.",
        ),
        DiagnosticDefinition(
            "EXCELLON_ROUTE_ARC_INVALID",
            "warning",
            "Invalid Excellon routed arc",
            "An Excellon routed arc failed geometric validation.",
            "Inspect its endpoint, center or radius encoding, and active coordinate format.",
        ),
        DiagnosticDefinition(
            "EXCELLON_UNITS_UNDECLARED",
            "warning",
            "Excellon units not declared",
            "Excellon dimensional data appeared before an explicit unit declaration.",
            "Declare METRIC, INCH, M71, or M72 before dimensional tool or coordinate data.",
        ),
        DiagnosticDefinition(
            "UNSUPPORTED_EXCELLON_SLOT",
            "warning",
            "Unsupported Excellon slot",
            "The Excellon G85 slot syntax is outside the supported subset.",
            "Regenerate the slot using supported G85 syntax or review with a CAM tool.",
        ),
        DiagnosticDefinition(
            "UNSUPPORTED_EXCELLON_ROUTE_SEQUENCE",
            "warning",
            "Unsupported Excellon route sequence",
            "The Excellon route sequence is not supported safely.",
            "Use the supported G00 positioning, M15 tool-down, routed motion, and M16/M17 tool-up sequence.",
        ),
        DiagnosticDefinition(
            "UNSUPPORTED_EXCELLON_ROUTE_ARC_SYNTAX",
            "warning",
            "Unsupported Excellon routed-arc syntax",
            "The routed arc does not match the supported I/J or X/Y/A radius forms.",
            "Regenerate the route using a supported arc encoding or review it with a CAM tool.",
        ),
        DiagnosticDefinition(
            "UNSUPPORTED_EXCELLON_ROUTE_ARC_CENTER",
            "warning",
            "Missing Excellon routed-arc center",
            "An I/J routed arc does not provide a usable center offset.",
            "Provide I and/or J center offsets for the routed arc.",
        ),
        DiagnosticDefinition(
            "UNSUPPORTED_EXCELLON_ICI_MODE",
            "warning",
            "Unsupported Excellon incremental mode",
            "The Excellon ICI incremental-input command is not recognized.",
            "Use ICI,ON, ICI,OFF, G90, or G91 as supported by the parser.",
        ),
        DiagnosticDefinition(
            "INVALID_EXCELLON_NUMERIC",
            "warning",
            "Invalid Excellon numeric value",
            "An Excellon coordinate, slot, route, or tool numeric value is invalid.",
            "Correct the numeric token and active coordinate format or unit declaration.",
        ),
        DiagnosticDefinition(
            "UNKNOWN_EXCELLON_STATEMENT",
            "warning",
            "Unknown Excellon statement",
            "The Excellon parser encountered an unrecognized statement.",
            "Review the statement against the supported Excellon subset before reconstruction.",
        ),
    ]
    for definition in definitions:
        catalog.add(definition)
    return catalog
