from __future__ import annotations
from dataclasses import dataclass

@dataclass(frozen=True)
class Capability:
    name:str
    status:str
    note:str

CAPABILITIES=[
    Capability("Generic manufacturing package input","implemented","Directory, single-file, ZIP, TAR, TAR.GZ, and TGZ ingestion with recursive discovery, content sniffing, X2/filename layer inference, parser-backed preflight, and bounded safe extraction."),
    Capability("Legacy Gerber compatibility","partial","Supports explicit MO or legacy G70/G71 units, absolute G90/FS-A and incremental G91/FS-I coordinates, standalone/modal D01/D02/D03 operations, UTF-8 BOM, once-only positive whole-image polarity via IPPOS, exact MI/SF/OF/IR image transforms for supported geometry, both AS axis-select forms as output-device-only no-ops, IN/LN comment metadata, G55 no-op, M01 optional stop, and M00/M02 termination. Header-only IP/AS/IN/MI/SF/OF/IR commands are rejected after the first coordinate statement, including D02 moves; duplicate/late header diagnostics are strict preflight blockers. IPNEG remains fail-closed because whole-image inversion is not modeled."),
    Capability("Gerber linear draws/flashes","partial","Positive-size C/R/O flashes plus standard P regular-polygon D03 flashes are supported, and zero-diameter C apertures are legal no-image D01/D03/G02/G03 objects. C/R/O/P D03 flashes support the standard centered round-hole modifier with transparent-hole semantics where applicable. Circular-aperture D01 draws remain Track objects; rectangular D01 sweeps are exact CopperRegion polygons and obround D01 sweeps use deterministic 0.005 mm chord-error-bounded polygonization. R/O linear sweeps/flashes and P flashes/draws support aperture transforms. Solid P D01 is materialized as an exact convex CopperRegion sweep. Holed P D01 plus other holed D01/G02/G03 draws remain fail-closed."),
    Capability("Gerber X2 file polarity","partial","Explicit Positive file polarity is accepted; Negative polarity fails closed because absence-of-material image inversion is not yet modeled."),
    Capability("Gerber layer polarity","partial","Dark LPD polarity is supported. LPC composes supported G36/G37 regions, C/R/O/P D03 flashes including supported round-hole variants, linear C/R/O/P D01 aperture sweeps, and circular-aperture G02/G03 tracks in source order into CopperRegion shells/holes. Aperture holes are transparent inside the flash operation rather than separate clear operations. P outer boundaries, regions, R flashes, and R linear sweeps are polygon-exact; C/O curved boundaries use deterministic inscribed chords with explicit provenance and a 0.005 mm maximum chord-error target. Tessellated circular-aperture arc tracks retain a conservative <=0.010 mm combined boundary-error budget. Outline geometry remains fail-closed."),
    Capability("Gerber aperture transforms","partial","Modal LM/LR/LS graphics-state transforms are applied to the original current aperture at object creation. C/R/O behavior is preserved; standard P D03 flashes and solid P D01 sweeps additionally apply LM mirroring before LR rotation to the original regular polygon, then LS scaling and supported whole-image IR. Orthogonal R/O flashes remain PadCandidate objects while transformed R/O and all P flashes use CopperRegion geometry when needed."),
    Capability("Gerber step-and-repeat","implemented","Supported draws, flashes, regions, outlines, and arcs are expanded deterministically with source provenance; malformed, non-positive, or over-limit repeat states fail closed and suppress permissive file geometry."),
    Capability("Gerber G75 circular arcs","partial","Multi-quadrant G02/G03 arcs use signed I/J center offsets with circular apertures and deterministic tessellation with explicit provenance."),
    Capability("Gerber simple aperture macros","partial","Single positive origin-centered circles, exact centered rectangular Code-20 vector-line (including deprecated Code-2), Code-21 center-line, deprecated Code-22 lower-left primitives, exact centered Code-4 outline rectangles/regular polygons, and origin-centered Code-5 regular polygons are reduced exactly to standard C/R/P apertures. Ordered macro-local variable definitions are evaluated from AD parameters, undefined variables evaluate as zero, and redefinition is rejected. Code-1 circles require exact four/five-modifier arity and finite evaluated values. Rectangular primitives preserve arbitrary finite rotation; Code-4 outlines must be explicitly closed and exactly reducible; Code-5 polygons require 3-12 integer vertices, positive circumscribed diameter, and finite rotation. Supported macro geometry composes with LM/LR/LS plus whole-image IR; other macro geometry remains fail-closed."),
