from __future__ import annotations
from dataclasses import dataclass

@dataclass(frozen=True)
class Capability:
    name:str
    status:str
    note:str

CAPABILITIES=[
    Capability("Generic manufacturing package input","implemented","Directory, single-file, ZIP, TAR, TAR.GZ, and TGZ ingestion with recursive discovery, content sniffing, X2/filename layer inference, parser-backed preflight, and bounded safe extraction."),
    Capability("Legacy Gerber compatibility","partial","Supports explicit MO or legacy G70/G71 units, absolute G90/FS-A and incremental G91/FS-I coordinates, standalone/modal D01/D02/D03 operations, UTF-8 BOM, once-only positive whole-image polarity via IPPOS, exact MI/SF/OF/IR image transforms for supported geometry, both AS axis-select forms as output-device-only no-ops, IN/LN comment metadata, G55 no-op, M01 optional stop, and M00/M02 termination. Header-only IP/AS/IN/MI/SF/OF/IR commands are rejected after the first coordinate statement, including D02 moves; duplicate/late header diagnostics are strict preflight blockers. IPNEG remains fail-closed because whole-image inversion is not modeled."),
    Capability("Gerber linear draws/flashes","partial","Positive-size C/R/O flashes plus standard P regular-polygon D03 flashes are supported, and zero-diameter C apertures are legal no-image D01/D03/G02/G03 objects. C/R/O/P D03 flashes support the standard centered round-hole modifier with transparent-hole semantics where applicable. Circular-aperture D01 draws remain Track objects; rectangular D01 sweeps are exact CopperRegion polygons and obround D01 sweeps use deterministic 0.005 mm chord-error-bounded polygonization. R/O linear sweeps/flashes and P flashes/draws support aperture transforms. Solid P D01 is materialized as an exact convex CopperRegion sweep. Holed P D01 plus other holed D01/G02/G03 draws remain fail-closed."),
    Capability("Gerber X2 file polarity","partial","Explicit Positive file polarity is accepted; Negative polarity fails closed because absence-of-material image inversion is not yet modeled."),
    Capability("Gerber layer polarity","partial","Dark LPD polarity is supported. LPC composes supported G36/G37 regions, C/R/O/P D03 flashes including supported round-hole variants, valid single-primitive Code-4 outline-macro D03 flashes, linear C/R/O/P D01 aperture sweeps, and circular-aperture G02/G03 tracks in source order into CopperRegion shells/holes. Aperture holes are transparent inside the flash operation rather than separate clear operations. P and Code-4 linear outline boundaries, regions, R flashes, and R linear sweeps are polygon-exact; C/O curved boundaries use deterministic inscribed chords with explicit provenance and a 0.005 mm maximum chord-error target. Tessellated circular-aperture arc tracks retain a conservative <=0.010 mm combined boundary-error budget. Edge.Cuts outline material remains fail-closed."),
    Capability("Gerber aperture transforms","partial","Modal LM/LR/LS graphics-state transforms are applied to the original current aperture at object creation. C/R/O behavior is preserved; standard P D03 flashes, solid P D01 sweeps, and general Code-4 outline-macro D03 flashes preserve their local template/primitive geometry through LM mirroring, LR rotation, LS scaling and supported whole-image IR. Orthogonal R/O flashes remain PadCandidate objects while transformed R/O, all P flashes, and general Code-4 flashes use CopperRegion geometry when needed."),
    Capability("Gerber step-and-repeat","implemented","Supported draws, flashes, regions, outlines, and arcs are expanded deterministically with source provenance; malformed, non-positive, or over-limit repeat states fail closed and suppress permissive file geometry."),
    Capability("Gerber G75 circular arcs","partial","Multi-quadrant G02/G03 arcs use signed I/J center offsets with circular apertures and deterministic tessellation with explicit provenance."),
    Capability("Gerber simple aperture macros","partial","Single positive origin-centered circles, exact centered rectangular Code-20 vector-line (including deprecated Code-2), Code-21 center-line, deprecated Code-22 lower-left primitives, reducible Code-4 outline rectangles/regular polygons, and origin-centered Code-5 regular polygons are reduced exactly to standard C/R/P apertures. Macro-local $n=expression definitions are evaluated in source order from AD-supplied variables; undefined variables evaluate to zero and any redefinition is invalid. Circle-macro reduction requires exactly four or five finite modifiers and rejects active-unit overflow. Other valid single-positive Code-4 simple contours with 3-5000 vertices are retained as exact linear-outline geometry for D03 flashes on material layers, including irregular, concave, and off-center shapes. Code-4 contours must be explicitly closed, finite, non-zero-length, non-self-touching, non-self-intersecting, and non-zero-area. General Code-4 D01 sweeps and Edge.Cuts flashes remain fail-closed. Supported macro geometry composes with LM/LR/LS plus whole-image IR and step-repeat; multiple/subtractive primitives, thermals, moires, and other unsupported macro geometry remain fail-closed."),
    Capability("Gerber G74 arcs/regions/macros","partial","Bounded G74 single-quadrant draws are supported when one <=90-degree center candidate is unambiguous. G36/G37 region statements support multiple explicitly closed contours with linear segments plus bounded G74 single-quadrant and G75 multi-quadrant G02/G03 circular boundaries and multiple cut-in holes per contour when every bridge is an opposite fully-coincident linear pair and all bridges in that contour share one axis direction (all horizontal or all vertical). Supported regions may participate in ordered LPD/LPC composition together with supported C/R/O/P D03 flashes, valid general Code-4 outline-macro D03 flashes, and linear C/R/O/P D01 aperture sweeps; R sweeps are exact while C/O curved boundaries are chord-error-bounded and explicitly evidenced. Resulting shells/holes participate in connectivity, DRC, transforms, provenance, and step-repeat. Disjoint fully-coincident cut-in topology, invalid/mixed-axis cut-ins, LPC mixed with outlines, Edge.Cuts regions, aperture blocks, and complex macros remain fail-closed."),
    Capability("Excellon drill hits","implemented","Point hits with explicitly declared metric/inch units and positive tool diameters; tool definitions before unit declaration or zero-diameter tools fail closed."),
    Capability("Excellon coordinate mode","implemented","Absolute G90/ICI,OFF and incremental G91/ICI,ON coordinates are supported for drill hits, G85 canned slots, and routed endpoints; incremental coordinates accumulate deterministically from the preceding coordinate."),
    Capability("Excellon G85 slots","implemented","Straight canned slots are reconstructed in absolute mode and in incremental G91/ICI,ON mode, where the start is relative to the preceding coordinate and the end is relative to the slot start."),
    Capability("Excellon linear routing","implemented","G00/M15/G01/M16 linear routed paths are reconstructed in absolute or incremental coordinate mode; malformed commands or invalid route-state transitions fail closed and suppress permissive file geometry."),
    Capability("Excellon routed arcs","partial","G02/G03 routed arcs support absolute or incremental endpoints with the bounded I/J center-offset subset plus standard XNC X/Y/A radius form (<=180 degrees), with deterministic tessellation; unsupported or invalid arc semantics fail closed and suppress permissive file geometry."),
    Capability("Excellon slots/routes","partial","G85 straight slots plus G00/M15/G01 linear routing and bounded G02/G03 circular routes are supported, including I/J center offsets and standard XNC A-radius form."),
    Capability("Physical copper connectivity","implemented","Geometry-overlap graph with deterministic IDs."),
    Capability("Logical net names","not_inferable","Manufacturing layers generally do not preserve original schematic net names."),
    Capability("Component hypotheses","implemented","Heuristic hypotheses only; never promoted to fact without evidence."),
    Capability("KiCad board export","experimental","Structured export; arbitrary Excellon routed paths are explicitly omitted until equivalent semantics are available."),
]
